spring.application.name=atm

spring.datasource.url=jdbc:postgresql://localhost:5432/atm_db
spring.datasource.username = postgres
spring.datasource.password = postgres

# none --> Does not change or create any database tables.
# create --> Drops existing database tables and creates new ones on startup. All existing data is lost.
# update --> Updates the database schema (adds new tables or columns) without deleting existing data.
# validate --> Validates that your entity classes match the existing database schema. Fails startup if they don't match.

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
